= Description

The hello world server and client demonstrate how to use Dart gRPC libraries to
perform unary RPCs.

See the definition of the hello world service in `protos/taekwondo_app.proto`.

 Run the sample code

To compile and run the example, assuming you are in the root of the taekwondo_app
folder, i.e., …/example/taekwondo_app/, first get the dependencies by running:

[source,sh]
----
$ pub get

----

== Run TCP sample code

Start the server:

[source,sh]
----
$ dart bin/server.dart
----

Likewise, to run the client:

[source,sh]
----
$ dart bin/client.dart
----

== Run UDS sample code

Start the server:

[source,sh]
----
$ dart bin/unix_server.dart
----

Likewise, to run the client:

[source,sh]
----
$ dart bin/unix_client.dart
----

____

*Note* the `UDS` only support *nix plantform.

____

If you have made changes to the message or service definition in
`protos/taekwondo_app.proto` and need to regenerate the corresponding Dart files,
you will need to have protoc version 3.0.0 or higher and the Dart protoc plugin
version 0.7.9 or higher on your PATH.

To install protoc, see the instructions on
https://developers.google.com/protocol-buffers/[the Protocol Buffers website].

The easiest way to get the Dart protoc plugin is by running

[source,sh]
----
$ pub global activate protoc_plugin
----
*иногда помогает при ошибке: dart pub global activate fvm*


and follow the directions to add `~/.pub-cache/bin` to your PATH, if you haven't
already done so.

You can now regenerate the Dart files by running

[source,sh]
----
$ protoc --dart_out=grpc:lib/grpc/generated -Iprotos protos/proto_service.proto
----